version: '3'
services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
