apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookexchange
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ym07th/bookexchange.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: bookexchange
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
